PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE analysis (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        timestamp INTEGER NOT NULL,
        content TEXT NOT NULL,
        type TEXT DEFAULT 'full'
      );
INSERT INTO analysis VALUES(1,1781065545580,'❌ 请先在 AI 分析面板中配置 API URL 和 API Key（点击右上角齿轮图标）。','full');
INSERT INTO analysis VALUES(2,1781068279735,'分析失败: Cannot convert argument to a ByteString because the character at index 7 has a value of 20320 which is greater than 255.','full');
INSERT INTO analysis VALUES(3,1781068435565,'分析失败: Cannot convert argument to a ByteString because the character at index 7 has a value of 20320 which is greater than 255.','full');
INSERT INTO analysis VALUES(4,1781068435565,'分析失败: Cannot convert argument to a ByteString because the character at index 7 has a value of 20320 which is greater than 255.','full');
INSERT INTO analysis VALUES(5,1781068895239,'分析失败: Cannot convert argument to a ByteString because the character at index 7 has a value of 20320 which is greater than 255.','full');
INSERT INTO analysis VALUES(6,1781068900189,'分析失败: Cannot convert argument to a ByteString because the character at index 7 has a value of 20320 which is greater than 255.','full');
INSERT INTO analysis VALUES(7,1781069452727,'分析失败: fetch failed','full');
INSERT INTO analysis VALUES(8,1781070364636,'分析失败: fetch failed','full');
INSERT INTO analysis VALUES(9,1781075598145,replace('1. 地缘政治风险: 中东局势升级，建议关注能源板块。\n2. 股票投资建议: 国防股（如 RTX, LMT）可能受益，可适量增持。\n3. 大宗商品: 黄金价格存在上涨空间，建议配置5%-10%。\n4. 加密货币: 比特币波动较大，谨慎操作。\n5. 网络安全: 近期恶意软件活跃，建议加强防护。\n6. 自然灾害: 菲律宾地震活跃，影响半导体供应链。\n7. 空间天气: Kp指数稳定，不影响通信。\n8. 航班动态: 全球航班量回升，航空股有反弹机会。\n9. 火灾风险: 亚马逊雨林火灾减少，环境改善。\n10. 全球经济: 美国通胀数据向好，美联储可能降息。','\n',char(10)),'full');
INSERT INTO analysis VALUES(10,1781075603136,replace('1. 地缘政治风险: 中东局势升级，建议关注能源板块。\n2. 股票投资建议: 国防股（如 RTX, LMT）可能受益，可适量增持。\n3. 大宗商品: 黄金价格存在上涨空间，建议配置5%-10%。\n4. 加密货币: 比特币波动较大，谨慎操作。\n5. 网络安全: 近期恶意软件活跃，建议加强防护。\n6. 自然灾害: 菲律宾地震活跃，影响半导体供应链。\n7. 空间天气: Kp指数稳定，不影响通信。\n8. 航班动态: 全球航班量回升，航空股有反弹机会。\n9. 火灾风险: 亚马逊雨林火灾减少，环境改善。\n10. 全球经济: 美国通胀数据向好，美联储可能降息。','\n',char(10)),'full');
INSERT INTO analysis VALUES(11,1781075727610,'分析失败: fetch failed','full');
INSERT INTO analysis VALUES(12,1781075729285,'分析失败: API 返回 404 - Not Found','full');
INSERT INTO analysis VALUES(13,1781076139752,replace('1. 【股票投资】建议关注半导体板块，全球芯片短缺持续影响供应链，相关企业或有估值修复机会。  \n2. 【全球风险】美联储加息预期升温，新兴市场货币可能承压，需警惕资本外流风险。  \n3. 【地缘政治】俄乌冲突持续影响能源市场，欧洲天然气价格波动较大，建议投资者谨慎操作。  \n4. 【自然灾害】近期全球无明显地震活动，但需持续关注环太平洋火山带潜在风险。  \n5. 【网络安全】暂无重大恶意软件威胁报告，但仍需保持系统更新以防零日漏洞攻击。  \n6. 【太空天气】当前太阳活动平稳，卫星通讯及电网运行无显著干扰风险。  \n7. 【投资机会】绿色能源板块受政策推动，风电与光伏企业或迎来新一轮增长。  \n8. 【经济预警】全球通胀压力高企，建议投资者增加抗通胀资产（如黄金、大宗商品）配置。  \n9. 【地缘动态】中美科技竞争加剧，供应链脱钩风险可能影响科技股表现。  \n10. 【市场趋势】加密货币市场波动加剧，监管不确定性下建议短线投资者保持谨慎。','\n',char(10)),'full');
INSERT INTO analysis VALUES(14,1781076501159,replace('1. 近期全球市场波动性较低，建议投资者保持观望态度，重点关注即将公布的美联储利率决议对市场的影响  \n2. 地缘政治预警：中东局势持续紧张，建议密切关注石油供应可能受到的冲击，能源板块存在潜在投资机会  \n3. 网络安全提醒：近期未检测到重大威胁，但仍建议企业定期更新系统补丁，防范潜在的零日漏洞攻击  \n4. 自然灾害监测：目前全球未报告重大自然灾害，但东南亚地区已进入台风季节，相关航运和供应链需保持警惕  \n5. 太空天气平稳：当前太阳活动处于低水平，不会对卫星通信和电网系统造成干扰，航空航天业务可正常进行  \n6. 投资机会提示：人工智能和量子计算领域持续获得政策支持，相关科技股可能迎来新一轮增长  \n7. 全球贸易动态：建议关注美欧贸易谈判进展，可能对汽车和农产品进出口产生显著影响  \n8. 加密货币观察：比特币价格相对稳定，但监管不确定性仍存，建议投资者控制数字资产配置比例  \n9. 健康风险提示：北半球即将进入流感季，医药板块可能迎来季节性行情  \n10. 宏观经济展望：全球通胀压力有所缓解，但主要经济体增长放缓的担忧仍然存在，建议分散投资组合风险','\n',char(10)),'full');
INSERT INTO analysis VALUES(15,1781076504992,replace('1. 【投资建议】当前全球市场数据缺失，建议投资者保持观望，密切关注即将公布的宏观经济指标和企业财报。  \n2. 【风险预警】地缘政治风险仍存，俄乌冲突和中东局势可能对能源及大宗商品市场造成波动，需警惕突发性事件。  \n3. 【网络安全】尽管暂无恶意软件威胁报告，企业仍需加强内部网络防护，防止钓鱼攻击和数据泄露。  \n4. 【自然灾害】近期未监测到重大地震或火灾活动，但夏季高温可能引发山火，需关注气象部门预警。  \n5. 【太空天气】当前空间天气平稳，但太阳活动周期进入活跃期，未来可能对卫星通信和电网造成干扰。  \n6. 【航空动态】航班数据暂未更新，建议旅客出行前确认航班状态，避免因天气或罢工延误行程。  \n7. 【能源市场】若地缘冲突升级，石油和天然气价格可能飙升，短线投资者可关注相关期货合约。  \n8. 【科技趋势】AI和量子计算领域持续突破，长期投资者可关注相关龙头企业的研发进展。  \n9. 【外汇市场】美元走势受美联储政策影响，若通胀数据超预期，可能引发汇率剧烈波动。  \n10. 【全球供应链】红海航运风险仍未完全消除，制造业企业需评估库存和替代运输方案。','\n',char(10)),'full');
INSERT INTO analysis VALUES(16,1781181467498,'分析失败: fetch failed','full');
INSERT INTO analysis VALUES(17,1781181468442,'分析失败: fetch failed','full');
INSERT INTO analysis VALUES(18,1781181591860,replace('1. 【投资建议】当前市场数据缺失，建议投资者保持观望，重点关注即将发布的全球主要经济体PMI数据以获取方向指引\n\n2. 【风险预警】数据空白期可能掩盖潜在市场风险，建议对投资组合进行防御性调整，增加现金和黄金配置比例\n\n3. 【地缘政治】关注近期中美高层会晤动向，缺乏即时数据时更需留意外交渠道释放的政策信号\n\n4. 【自然灾害】虽无地震报告，但环太平洋地震带已进入活跃周期，建议相关地区企业检查应急预案\n\n5. 【网络安全】数据空白不等于安全，建议企业立即检查防火墙和入侵检测系统是否正常运行\n\n6. 【太空天气】太阳活动周期接近峰值，即使当前无警报，卫星运营商仍需做好应对太阳风暴的准备工作\n\n7. 【大宗商品】关键数据缺失期间，原油市场对地缘政治消息将更加敏感，建议控制能源期货仓位\n\n8. 【外汇市场】在缺乏经济数据指引时，美元指数可能维持区间震荡，短线操作需谨慎\n\n9. 【债券市场】建议关注美国10年期国债收益率的技术支撑位，数据真空期债市波动可能加剧\n\n10. 【AI监管】全球AI安全峰会即将召开，科技板块可能受政策预期影响，建议提前布局相关对冲策略','\n',char(10)),'full');
INSERT INTO analysis VALUES(19,1781181594378,replace('1. **股市观望建议**：当前全球主要市场数据缺失，建议投资者保持观望，等待更明确的市场信号。  \n\n2. **地缘政治风险提示**：近期无显著地缘政治冲突报告，但仍需关注中东和东欧局势的潜在变化。  \n\n3. **自然灾害监测**：目前未检测到重大地震或火山活动，但建议持续关注环太平洋地震带的动态。  \n\n4. **网络安全提醒**：尽管当前未报告大规模网络攻击，企业仍应加强基础防护，防范勒索软件和钓鱼攻击。  \n\n5. **航空安全建议**：航班动态暂无异常，但出行前建议查询实时航班信息，以防临时变动。  \n\n6. **太空天气监测**：太阳活动平稳，暂无强烈太阳风暴预警，卫星通信和电网运行风险较低。  \n\n7. **经济政策关注点**：美联储及欧央行政策动向未更新，投资者需留意近期利率决议的潜在影响。  \n\n8. **大宗商品趋势**：石油与黄金价格暂无剧烈波动，但地缘紧张或经济数据可能引发短期震荡。  \n\n9. **企业财报季预警**：若处于财报季尾声，建议复盘企业表现，调整中长期投资策略。  \n\n10. **全球供应链观察**：暂无重大中断报告，但海运成本及区域冲突可能影响未来物流效率。  \n\n（注：因实时数据匮乏，部分分析基于常规风险框架。建议通过权威平台补充验证。）','\n',char(10)),'full');
INSERT INTO analysis VALUES(20,1781181864425,'分析失败: fetch failed','full');
INSERT INTO analysis VALUES(21,1781181943100,'分析失败: fetch failed','full');
INSERT INTO analysis VALUES(22,1781181947949,'分析失败: fetch failed','full');
CREATE TABLE infosec_processed (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  title TEXT NOT NULL,
  raw_content TEXT,
  summary TEXT,
  category TEXT,
  risk_score INTEGER,
  entities TEXT,
  source TEXT,
  published TEXT,
  lat REAL,
  lng REAL,
  created_at INTEGER DEFAULT (strftime('%s','now'))
, link TEXT);
INSERT INTO infosec_processed VALUES(420,'Ongoing exploitation of Cisco Catalyst SD-WAN vulnerabilities','思科SD-WAN多漏洞正遭利用，攻击者获取管理员权限并部署多种恶意工具，需立即修补。','思科SD-WAN漏洞遭利用','漏洞',85,'思科,Catalyst SD-WAN,CVE-2026-20182,UAT-8616,ZeroZenX Labs,XenShell,Godzilla,Behinder','AlienVault OTX','2026-06-13T20:00:40.123000',NULL,NULL,1781417945,'https://otx.alienvault.com/pulse/6a062c38dfdb5434bb2f0876');
INSERT INTO infosec_processed VALUES(421,'ClickFix Evolves with PySoxy Proxying','ClickFix攻击链使用PySoxy创建冗余加密通道，实现持久化访问，从一次性执行演变为模块化后渗透。','ClickFix结合PySoxy代理攻击','恶意软件',75,'ClickFix, PySoxy, PowerShell, SOCKS5, 社会工程学, 计划任务, C2','AlienVault OTX','2026-06-12T16:17:03.982000',NULL,NULL,1781417953,'https://otx.alienvault.com/pulse/6a04a9a171b2ad5ef57d9993');
INSERT INTO infosec_processed VALUES(422,'Python Backdoor Threat Analysis Following an AI Deepfake Impersonation Campaign','APT37通过钓鱼邮件传播Python后门，利用LNK文件混淆技术实现远程控制。','APT37 Python后门攻击','恶意软件',75,'APT37, Python后门, 钓鱼邮件, LNK文件, 环境变量混淆, C2服务器','AlienVault OTX','2026-06-12T16:17:03.982000',NULL,NULL,1781417964,'https://otx.alienvault.com/pulse/6a04a9a090a64de310cb0568');
INSERT INTO infosec_processed VALUES(423,'LBIOC-20260071 - The Gentlemens Leak','2025年下半年的新兴勒索组织，与Qilin有关，跨平台攻击。','绅士勒索软件组织','黑客组织',75,'The Gentlemen, Qilin, hastalamuerte, SystemBC','AlienVault OTX','2026-06-12T09:05:02.916000',NULL,NULL,1781417974,'https://otx.alienvault.com/pulse/6a043fa88d6fd92063164a04');
INSERT INTO infosec_processed VALUES(424,'Targeted espionage against Cambodian government entities','Khmer Shadow组织利用NIGHTFORGE加载器攻击柬埔寨政府部门，采用高级规避技术和COM持久化机制。','柬埔寨政府遭网络间谍攻击','黑客组织',70,'Khmer Shadow, NIGHTFORGE, 柬埔寨政府, 信息收集局, 公共工程与运输部, VMwareNamespaceCmd.exe, Havoc Demon','AlienVault OTX','2026-06-11T14:41:08.187000',NULL,NULL,1781417982,'https://otx.alienvault.com/pulse/6a2aa0fe417d1a6f2b89eec1');
INSERT INTO infosec_processed VALUES(425,'From external espionage to domestic targeting','OceanLotus组织利用SPECTRALVIPER后门攻击越南金融和基建机构，可能与反腐行动相关。','越南APT转向国内间谍','黑客组织',70,'OceanLotus, SPECTRALVIPER, FireAnt Metakit, 越南, Blazing Furnace','AlienVault OTX','2026-06-11T14:30:15.457000',NULL,NULL,1781417991,'https://otx.alienvault.com/pulse/6a2ac312c98386d398eab284');
INSERT INTO infosec_processed VALUES(426,'Sniper''s Nest: From Brand Impersonation to Browser Hijacking and CPA Fraud','假冒政治人物和品牌，通过虚假优惠诱导用户，滥用浏览器通知和重定向进行网络钓鱼和欺诈。','SniperDz钓鱼平台','攻击事件',75,'SniperDz, Facebook, Linktree, Linkbio, 中东, 北非, 网络钓鱼, 品牌假冒','AlienVault OTX','2026-06-11T14:27:52.839000',NULL,NULL,1781418002,'https://otx.alienvault.com/pulse/6a2aa0d6db4e2c52648e2ed7');
INSERT INTO infosec_processed VALUES(427,'Vibe Hacking: Two AI-Augmented Campaigns Target Government and Financial Sectors in Latin America','两种AI增强黑客活动分别用西语和葡语攻击拉美政府与金融机构，利用AI动态生成工具规避检测。','拉美AI黑客攻击政府金融','攻击事件',75,'SHADOW-AETHER-040, SHADOW-AETHER-064, 拉丁美洲, 政府, 金融机构, AI代理, ProxyChains, SSH, Chisel, Neo-reGeorg, CrackMapExec, Impacket','AlienVault OTX','2026-06-11T08:16:08.337000',NULL,NULL,1781418010,'https://otx.alienvault.com/pulse/6a02ea171e7005022d5c8a6f');
INSERT INTO infosec_processed VALUES(428,'China-Linked Fake Consulting Sites Targeting US Clearance Holders Seized','美当局查封13个与中国情报相关的虚假咨询网站，这些网站伪装成合法公司招募美国安全许可持有者窃取机密信息。','中国虚假咨询网站招募美情报人员','攻击事件',75,'中国、美国、虚假咨询网站、安全许可持有者、13个域名、Upwork、Expertia AI、Hubstaff Talent、加密货币、AI生成的头像','AlienVault OTX','2026-06-11T07:38:33.382000',NULL,NULL,1781418033,'https://otx.alienvault.com/pulse/6a2a625931731a23250efb39');
INSERT INTO infosec_processed VALUES(429,'Fake Software Tutorials on TikTok Spread Vidar Stealer','黑客利用TikTok和Instagram虚假软件教程传播Vidar信息窃取程序，通过AI语音和私信链接诱导用户下载。','TikTok虚假教程传播Vidar窃密器','恶意软件',70,'TikTok, Instagram Reels, Vidar, PowerShell, 恶意链接, 假冒Windows账户','AlienVault OTX','2026-06-11T07:37:24.272000',NULL,NULL,1781418039,'https://otx.alienvault.com/pulse/6a298f548047c70cc9e2f4ee');
INSERT INTO infosec_processed VALUES(430,'SilabRAT, What''s Your Power?','SilabRAT is an advanced Remote Access Trojan offered as Malware-as-a-Service on Darkweb forums since late 2025, developed by threat actor o1oo1 and sold for $5,000 monthly. This financially-motivated tool focuses on credential theft and cryptocurrency operations, featuring Hidden Virtual Network Computing for invisible remote control, browser profile cloning to bypass session protections, and automated cryptocurrency wallet password cracking. The RAT bypasses Chrome App-Bound Encryption, performs session hijacking, and includes keylogging, clipboard monitoring, and remote desktop capabilities. Distributed through phishing and ClickFix campaigns with operator-hosted infrastructure, SilabRAT uses ChaCha20-Poly1305 encryption for command-and-control communications. The developer also offers AsmCrypt, a companion crypter service, creating a complete malware bundle from evasion to execution and remote control.','SilabRAT, What''s Your Power?','威胁情报',50,'','AlienVault OTX','2026-06-10T13:45:08.713000',NULL,NULL,1781418055,'https://otx.alienvault.com/pulse/6a2951665d658e753b489765');
INSERT INTO infosec_processed VALUES(431,'Ransomware Analysis: Go Binary and Fast Encryption','绅士勒索软件为RaaS团伙，已攻击全球1570组织，采用部分加密技术，存在密钥恢复漏洞。','绅士勒索软件分析','恶意软件',60,'The Gentlemen, Storm-2697, Qilin, BreachForums, X25519, XChaCha20, CWE-244','AlienVault OTX','2026-06-10T13:44:10.922000',NULL,NULL,1781418071,'https://otx.alienvault.com/pulse/6a2951722e6ca0cbaaac430b');
INSERT INTO infosec_processed VALUES(432,'Poisoning the well: AI supply chain attacks on Hugging Face and OpenClaw','攻击者利用AI平台在模型和数据集中嵌入恶意代码，分发特洛伊木马和挖矿软件。','AI平台恶意代码植入','恶意软件',70,'Hugging Face, OpenClaw, AI供应链, 恶意代码, 模型, 数据集, 特洛伊木马, 加密货币挖矿器, AMOS窃取器','AlienVault OTX','2026-06-10T11:10:28.171000',NULL,NULL,1781418085,'https://otx.alienvault.com/pulse/6a01c2363e7f67fcbed473cb');
INSERT INTO infosec_processed VALUES(433,'PHISH ALERT: Press Play for Compromise — Voicemail Phishing Kit Bundles SSO Hijacking, Credential Theft, and RMM Delivery','利用语音邮件HTML附件劫持M365会话，结合OAuth漏洞与多向量攻击窃取凭证。','语音邮件钓鱼套件','攻击事件',75,'语音邮件钓鱼套件,OAuth漏洞,Microsoft 365,凭据收集,土耳其域名,虚假登录,RMM部署','AlienVault OTX','2026-06-10T11:00:38.503000',NULL,NULL,1781418097,'https://otx.alienvault.com/pulse/6a2943210c24d6920786a101');
INSERT INTO infosec_processed VALUES(434,'Phishing Attacks Leverage TikTok, Instagram Reels','攻击者利用TikTok和Instagram Reels发布虚假教程和视频，诱导用户访问恶意网站下载信息窃取软件。','短视频平台钓鱼攻击','攻击事件',50,'TikTok, Instagram Reels, Vidarstealer, 社会工程学攻击, 信息窃取软件, PowerShell命令','AlienVault OTX','2026-06-10T10:46:05.809000',NULL,NULL,1781418105,'https://otx.alienvault.com/pulse/6a287385c06d53a7cf5a8a30');
INSERT INTO infosec_processed VALUES(435,'Technical Analysis of MLTBackdoor','MLTBackdoor是新型恶意软件，采用高级混淆技术，通过汽车相关网页传播，具有反分析能力和持久性机制。','MLTBackdoor恶意软件分析','恶意软件',75,'MLTBackdoor, ClickFix, 混合布尔算术, 控制流扁平化, 椭圆曲线Diffie-Hellman, 域名生成算法','AlienVault OTX','2026-06-10T10:44:32.069000',NULL,NULL,1781418117,'https://otx.alienvault.com/pulse/6a28738628b044b8202032a9');
INSERT INTO infosec_processed VALUES(436,'From Fake Amazon Security Alert to HarborWatch Agent: ClickFix Delivery of a Custom Monitoring RAT','假冒亚马逊安全警报钓鱼活动，通过ClickFix技术分发HarborWatch定制远程访问木马。','亚马逊钓鱼分发定制RAT','恶意软件',70,'亚马逊,HarborWatch Agent,ClickFix,PowerShell,mysql.exe,Harbor Sentinel,远程访问木马','AlienVault OTX','2026-06-10T10:43:20.227000',NULL,NULL,1781418122,'https://otx.alienvault.com/pulse/6a28363f58453c0b99062360');
INSERT INTO infosec_processed VALUES(437,'Active Exploitation of Check Point VPN Authentication Bypass (CVE-2026-50751)','VPN认证绕过漏洞遭积极利用，攻击者无需密码建立会话，已影响全球数十组织。','Check Point VPN认证绕过','漏洞',85,'Check Point VPN, CVE-2026-50751, 认证绕过, IKEv1协议, 麒麟勒索软件','AlienVault OTX','2026-06-10T10:41:23.012000',NULL,NULL,1781418131,'https://otx.alienvault.com/pulse/6a283636822bcec71a644940');
INSERT INTO infosec_processed VALUES(438,'Honeypot reveals botnet exploiting scriptText to launch DDoS attacks on game servers','攻击者利用Jenkins漏洞部署多平台DDoS僵尸网络，针对游戏服务器发动多种攻击。','游戏服务器遭DDoS僵尸攻击','攻击事件',60,'Jenkins, scriptText, DDoS僵尸网络, 游戏服务器, 远程代码执行, 多平台, Valve Source Engine, 越南','AlienVault OTX','2026-06-10T08:24:08.893000',NULL,NULL,1781418143,'https://otx.alienvault.com/pulse/6a0199674dd4cf450633dd32');
INSERT INTO infosec_processed VALUES(439,'Needle: Inside a Modular Crypto-Stealing C2 That Left Its Keys in the Malware','模块化恶意软件伪装钱包应用攻击用户，已致近两千受害者损失。','Needle加密窃取平台','恶意软件',70,'Needle, MetaMask, Phantom, Trust Wallet, Exodus, Trezor, Ledger, Rust, C2 API, ETH, ASN 202412','AlienVault OTX','2026-06-10T08:24:08.893000',NULL,NULL,1781418151,'https://otx.alienvault.com/pulse/6a0198399994be750fe044cd');
INSERT INTO infosec_processed VALUES(440,'CVE-2026-11455','A vulnerability was determined in FoundationAgents MetaGPT up to 0.8.2. Affected by this issue is the function check_cmd_exists of the file metagpt/utils/common.py. This manipulation of the argument mermaid.path causes command injection. The attack may be initiated remotely. A high degree of complexity is needed for the attack. The exploitation is known to be difficult. The exploit has been publicly disclosed and may be utilized. The project was informed of the problem early through an issue report but has not responded yet.','MetaGPT命令注入漏洞，可通过mermaid.path参数远程执行命令','漏洞',50,'FoundationAgents MetaGPT, metagpt/utils/common.py, check_cmd_exists函数','NVD','2026-06-07T09:16:20.403',NULL,NULL,1781418159,'https://nvd.nist.gov/vuln/detail/CVE-2026-11455');
INSERT INTO infosec_processed VALUES(441,'CVE-2026-11456','A vulnerability was identified in Chanjet CRM 1.0. This affects an unknown part of the file /tools/jxf_dump_systable.php of the component HTTP GET Request Handler. Such manipulation of the argument gblOrgID leads to sql injection. The attack may be launched remotely. The exploit is publicly available and might be used. The vendor was contacted early about this disclosure but did not respond in any way.','Chanjet CRM存在SQL注入漏洞，可通过gblOrgID参数远程利用','漏洞',73,'HTTP GET Request Handler','NVD','2026-06-07T09:16:21.673',NULL,NULL,1781418165,'https://nvd.nist.gov/vuln/detail/CVE-2026-11456');
INSERT INTO infosec_processed VALUES(442,'CVE-2026-11457','A security flaw has been discovered in erzhongxmu JeeWMS up to 141740afb2ba14d441c82a833d0a418d07ca2d69. This vulnerability affects unknown code of the file /base-boot/jmreport/testConnection of the component JimuReport test-connection Endpoint. Performing a manipulation of the argument dbType/dbDriver/dbUrl/dbUsername/dbPassword results in injection. Remote exploitation of the attack is possible. The exploit has been released to the public and may be used for attacks. This product follows a rolling release approach for continuous delivery, so version details for affected or updated releases are not provided. The vendor was contacted early about this disclosure but did not respond in any way.','JeeWMS JimuReport组件存在远程注入漏洞','漏洞',73,'JimuReport test-connection Endpoint','NVD','2026-06-07T09:16:21.843',NULL,NULL,1781418171,'https://nvd.nist.gov/vuln/detail/CVE-2026-11457');
INSERT INTO infosec_processed VALUES(443,'CVE-2026-11458','A weakness has been identified in erzhongxmu JeeWMS up to 141740afb2ba14d441c82a833d0a418d07ca2d69. This issue affects some unknown processing of the file /base-boot/actuator of the component Boot Actuator Endpoint. Executing a manipulation can lead to information disclosure. The attack can be executed remotely. The exploit has been made available to the public and could be used for attacks. This product implements a rolling release for ongoing delivery, which means version information for affected or updated releases is unavailable. The vendor was contacted early about this disclosure but did not respond in any way.','JeeWMS Boot Actuator组件存在远程信息泄露漏洞','漏洞',53,'Boot Actuator Endpoint','NVD','2026-06-07T09:16:22.050',NULL,NULL,1781418177,'https://nvd.nist.gov/vuln/detail/CVE-2026-11458');
INSERT INTO infosec_processed VALUES(444,'CVE-2026-11459','A security vulnerability has been detected in SecureAge CatchPulse up to 10.9.3. Impacted is an unknown function in the library saappctl.sys of the component IOCTL Handler. The manipulation leads to information disclosure. Local access is required to approach this attack. The exploit has been disclosed publicly and may be used.','SecureAge CatchPulse存在信息泄露漏洞','漏洞',33,'saappctl.sys','NVD','2026-06-07T10:16:21.863',NULL,NULL,1781418181,'https://nvd.nist.gov/vuln/detail/CVE-2026-11459');
INSERT INTO infosec_processed VALUES(445,'CVE-2026-49494','Comodo Internet Security''s firewall driver Inspect.sys contains an integer underflow in its IPv6 packet parser. The parser decrements an unsigned 64-bit payload-length value (taken from the IPv6 fixed header''s payload length field) by the size of each IPv6 extension header without validating it, so a packet whose declared payload length is smaller than the sum of its extension-header lengths underflows the value to a near-maximal 64-bit integer. Because IPv6 parsing occurs before firewall rule enforcement, a remote, unauthenticated attacker can send a single crafted IPv6 packet - even to a host with all ports blocked - to trigger an out-of-bounds read (and, on a separate code path, an oversized memcpy) in the Windows kernel at DISPATCH_LEVEL, crashing the system (BSOD).','Comodo防火墙IPv6解析整数下溢可致系统崩溃','漏洞',75,'Comodo Internet Security防火墙驱动Inspect.sys','NVD','2026-06-07T13:16:20.927',NULL,NULL,1781418189,'https://nvd.nist.gov/vuln/detail/CVE-2026-49494');
INSERT INTO infosec_processed VALUES(446,'CVE-2026-11460','A flaw has been found in Boost Serialization up to 1.91. The impacted element is an unknown function. This manipulation causes improper validation of specified type of input. It is possible to initiate the attack remotely. The exploit has been published and may be used. The maintainer was notified on Aug 2025 and a disclosure deadline was set for 90 days. The maintainer acknowledged but postponed indefinitely citing time concerns. No patch is currently available and the disclosure deadline has expired.','Boost Serialization库存在远程输入验证漏洞','漏洞',73,'Boost Serialization','NVD','2026-06-07T20:16:39.993',NULL,NULL,1781418194,'https://nvd.nist.gov/vuln/detail/CVE-2026-11460');
INSERT INTO infosec_processed VALUES(447,'CVE-2026-11461','A vulnerability has been found in NousResearch hermes-agent up to 0.12.0. This affects the function resolve_session_by_title of the file hermes_state.py of the component resume Endpoint. Such manipulation of the argument Title leads to authorization bypass. It is possible to launch the attack remotely. The exploit has been disclosed to the public and may be used. The vendor was contacted early about this disclosure but did not respond in any way.','hermes-agent授权绕过漏洞，可通过远程操作Title参数利用','漏洞',63,'hermes-agent resume endpoint','NVD','2026-06-07T22:16:22.547',NULL,NULL,1781418200,'https://nvd.nist.gov/vuln/detail/CVE-2026-11461');
INSERT INTO infosec_processed VALUES(448,'CVE-2026-11462','A vulnerability was found in Chengdu Everbrite Network Technology BeikeShop up to 1.6.0.22. This impacts the function callback of the file plugins/Stripe/Controllers/StripeController.php of the component Stripe Plugin. Performing a manipulation of the argument Request results in improper authorization. The attack can be initiated remotely. The exploit has been made public and could be used. The patch is named 6719e0fc690ea0a998452092862e0f0a17c65968. It is suggested to install a patch to address this issue.','BeikeShop插件不当授权漏洞，可通过远程请求参数操纵利用','漏洞',73,'Stripe Plugin','NVD','2026-06-07T23:16:41.040',NULL,NULL,1781418206,'https://nvd.nist.gov/vuln/detail/CVE-2026-11462');
INSERT INTO infosec_processed VALUES(449,'CVE-2026-11463','A vulnerability was determined in USCiLab Cereal up to 1.3.2. Affected is an unknown function of the component Shared Pointer Handler. Executing a manipulation can lead to type confusion. The attack can be launched remotely. The exploit has been publicly disclosed and may be utilized. The vendor was contacted early about this disclosure.','USCiLab Cereal共享指针处理器存在类型混淆漏洞','漏洞',73,'Shared Pointer Handler','NVD','2026-06-07T23:16:41.697',NULL,NULL,1781418212,'https://nvd.nist.gov/vuln/detail/CVE-2026-11463');
INSERT INTO infosec_processed VALUES(450,'CVE-2026-11464','A vulnerability was identified in JeecgBoot up to 3.9.2. Affected by this vulnerability is the function queryPageList of the file src\main\java\org\jeecg\modules\system\controller\SysUserController.java of the component User List Endpoint. The manipulation of the argument salt leads to information disclosure. The attack may be initiated remotely. The attack is considered to have high complexity. The exploitation appears to be difficult. The exploit is publicly available and might be used. A fix is planned for the upcoming release.','JeecgBoot用户列表接口存在信息泄露漏洞','漏洞',31,'User List Endpoint','NVD','2026-06-07T23:16:41.890',NULL,NULL,1781418222,'https://nvd.nist.gov/vuln/detail/CVE-2026-11464');
INSERT INTO infosec_processed VALUES(451,'CVE-2026-11465','A security flaw has been discovered in songquanpeng one-api up to 0.6.11-preview.7. Affected by this issue is the function Redeem of the file model/redemption.go of the component Redemption Code Top-Up Endpoint. The manipulation results in business logic errors. The attack may be launched remotely. The attack requires a high level of complexity. The exploitation is known to be difficult. The exploit has been released to the public and may be used for attacks. The pull request to fix this issue awaits acceptance.','one-api兑换码功能存在业务逻辑漏洞','漏洞',31,'Redemption Code Top-Up Endpoint','NVD','2026-06-07T23:16:42.060',NULL,NULL,1781418230,'https://nvd.nist.gov/vuln/detail/CVE-2026-11465');
INSERT INTO infosec_processed VALUES(452,'CVE-2026-11466','A weakness has been identified in zilliztech deep-searcher up to 0.0.2. This affects the function CollectionRouter.invoke of the file deepsearcher/agent/collection_router.py. This manipulation of the argument kwargs causes improper access controls. Remote exploitation of the attack is possible. The exploit has been made available to the public and could be used for attacks. The pull request to fix this issue awaits acceptance.','deep-searcher访问控制漏洞，可远程利用','漏洞',54,'zilliztech deep-searcher','NVD','2026-06-07T23:16:42.213',NULL,NULL,1781418236,'https://nvd.nist.gov/vuln/detail/CVE-2026-11466');
INSERT INTO infosec_processed VALUES(453,'CVE-2026-11467','A security vulnerability has been detected in jishenghua jshERP up to 3.6. This vulnerability affects the function addAccountHeadAndDetail of the file jshERP-boot/src/main/java/com/jsh/erp/service/AccountHeadService.java of the component addAccountHeadAndDetail Endpoint. Such manipulation of the argument fileName leads to path traversal. The attack can be executed remotely. The exploit has been disclosed publicly and may be used. The project was informed of the problem early through an issue report but has not responded yet.','jshERP系统存在路径遍历漏洞，可通过远程攻击利用','漏洞',54,'jshERP addAccountHeadAndDetail Endpoint','NVD','2026-06-08T00:16:42.230',NULL,NULL,1781418246,'https://nvd.nist.gov/vuln/detail/CVE-2026-11467');
INSERT INTO infosec_processed VALUES(454,'CVE-2026-11468','A vulnerability was detected in SourceCodester Hospitals Patient Records Management System 1.0. This issue affects some unknown processing of the file /admin/?page=room_types. Performing a manipulation of the argument room results in cross site scripting. The attack is possible to be carried out remotely. The exploit is now public and may be used.','医院患者记录管理系统存在XSS漏洞，可通过room参数触发','漏洞',24,'SourceCodester Hospitals Patient Records Management System 1.0','NVD','2026-06-08T00:16:42.387',NULL,NULL,1781418254,'https://nvd.nist.gov/vuln/detail/CVE-2026-11468');
INSERT INTO infosec_processed VALUES(455,'CVE-2026-11469','A flaw has been found in jishenghua jshERP up to 3.6. Impacted is the function insertPlatformConfig of the file jshERP-boot/src/main/java/com/jsh/erp/service/PlatformConfigService.java of the component platformConfig Add Endpoint. Executing a manipulation of the argument platformValue can lead to server-side request forgery. The attack may be performed from remote. The exploit has been published and may be used. The project was informed of the problem early through an issue report but has not responded yet.','jshERP平台配置组件存在服务器端请求伪造漏洞','漏洞',47,'platformConfig Add Endpoint','NVD','2026-06-08T00:16:42.580',NULL,NULL,1781418261,'https://nvd.nist.gov/vuln/detail/CVE-2026-11469');
INSERT INTO infosec_processed VALUES(456,'CVE-2026-11470','A vulnerability has been found in hs-web hsweb-framework up to 5.0.1. The affected element is the function denied of the file hsweb-system/hsweb-system-file/src/main/java/org/hswebframework/web/file/FileUploadProperties.java of the component File Upload. The manipulation of the argument filename leads to path traversal. It is possible to initiate the attack remotely. The exploit has been disclosed to the public and may be used. The identifier of the patch is 8009845b577d8a2c4bbf4fdd8e8913799a714be6. It is suggested to install a patch to address this issue.','hsweb-framework文件上传组件路径遍历漏洞','漏洞',63,'文件上传组件','NVD','2026-06-08T01:16:22.433',NULL,NULL,1781418267,'https://nvd.nist.gov/vuln/detail/CVE-2026-11470');
INSERT INTO infosec_processed VALUES(457,'CVE-2026-11471','A vulnerability was found in SourceCodester Class and Exam Timetabling System 1.0. The impacted element is an unknown function of the file /index2.php. The manipulation of the argument Password results in sql injection. It is possible to launch the attack remotely. The exploit has been made public and could be used.','SourceCodester考试排课系统1.0存在SQL注入漏洞','漏洞',73,'SourceCodester Class and Exam Timetabling System 1.0','NVD','2026-06-08T01:16:22.600',NULL,NULL,1781418276,'https://nvd.nist.gov/vuln/detail/CVE-2026-11471');
INSERT INTO infosec_processed VALUES(458,'CVE-2026-11472','A vulnerability was determined in SourceCodester Class and Exam Timetabling System 1.0. This affects an unknown function of the file /index1.php. This manipulation of the argument Password causes sql injection. The attack can be initiated remotely. The exploit has been publicly disclosed and may be utilized.','SourceCodester考试排课系统1.0存在SQL注入漏洞','漏洞',73,'SourceCodester Class and Exam Timetabling System 1.0','NVD','2026-06-08T01:16:22.760',NULL,NULL,1781418282,'https://nvd.nist.gov/vuln/detail/CVE-2026-11472');
INSERT INTO infosec_processed VALUES(459,'CVE-2026-11473','A vulnerability was identified in jflyfox jfinal_cms up to 5.1.0. This impacts the function list of the file AdvicefeedbackController.java. Such manipulation of the argument orderBy leads to sql injection. The attack can be launched remotely. The project was informed of the problem early through an issue report but has not responded yet.','jflyfox jfinal_cms存在SQL注入漏洞','漏洞',63,'jflyfox jfinal_cms','NVD','2026-06-08T01:16:22.917',NULL,NULL,1781418289,'https://nvd.nist.gov/vuln/detail/CVE-2026-11473');
DELETE FROM sqlite_sequence;
INSERT INTO sqlite_sequence VALUES('analysis',22);
INSERT INTO sqlite_sequence VALUES('infosec_processed',459);
CREATE INDEX idx_timestamp ON analysis(timestamp);
CREATE INDEX idx_infosec_created ON infosec_processed(created_at);
CREATE INDEX idx_unique_source_title ON infosec_processed(source, title);
COMMIT;
